[project]
name = "hermes-trading"
version = "0.1.0"
description = "Trading bot framework core"
requires-python = ">=3.10"
dependencies = [
    "ccxt>=4.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
